common: &SHARED
  adapter: postgresql
  username: postgres
  password: pg
  pool: 5
  encoding: unicode
  min_messages: WARNING

development:
  <<: *SHARED
  database: lyonrb_development

test:
  <<: *SHARED
  database: lyonrb_test

production:
  <<: *SHARED
  database: lyonrb_production
